# Generated by Django 5.1.7 on 2025-03-19 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTarea',
            fields=[
                ('id_estado', models.BigAutoField(db_comment='IDENTIFICADOR DE LA TAREA.', primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(db_comment='NOMBRE DEL ESTADO')),
                ('descripcion_estado', models.CharField(blank=True, db_comment='DESCRIPCION DEL ESTADO DE LA TAREA', null=True)),
                ('estado', models.BooleanField(db_comment='ESTADO ACTIVO O INACTIVO')),
            ],
            options={
                'db_table': 'estado_tarea',
                'db_table_comment': 'ESTADO DE LA TAREA',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.BigAutoField(db_comment='IDENTIFICADOR DEL PROYECTO', primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(db_comment='FECHA DE CREACION DEL PROYECTO')),
                ('titulo', models.CharField(db_comment='TITULO DEL PROYECTO')),
                ('estado', models.BooleanField(db_comment='ESTADO ACTIVO O INACTIVO')),
            ],
            options={
                'db_table': 'proyecto',
                'db_table_comment': 'TABLA DONDE SE ALMACENA LOS PROYECTOS',
            },
        ),
        migrations.CreateModel(
            name='ProyectoUsuarioRol',
            fields=[
                ('id_proyecto_usuario_rol', models.BigAutoField(db_comment='IDENTIFDICADOR DE LA RELACION ENTRE LAS TABLAS PROYECTO, ROL, USUARIO', primary_key=True, serialize=False)),
                ('estado', models.BooleanField(db_comment='ESTADO ACTIVO O INACTIVO')),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', db_comment='IDENTIFICADOR DEL PROYECTO', on_delete=django.db.models.deletion.CASCADE, to='app.proyecto')),
                ('id_rol', models.ForeignKey(db_column='id_group', db_comment='IDENTIFICADOR DEL ROL', on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('id_user', models.ForeignKey(db_column='id_user', db_comment='IDENTIFICADOR DEL USUARIO', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proyecto_usuario_rol',
                'db_table_comment': 'TABLA DONDE SE INDICA QUE USUARIO ESTA RELACIONADO CON CADA PROYECTO, Y EL ROL QUE TENDRA',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.BigAutoField(db_comment='IDENTIFICADOR DE LA TAREA', primary_key=True, serialize=False)),
                ('usuario_rol', models.CharField(blank=True, db_comment='USUARIO ASIGNADO A LA TAREA', null=True)),
                ('titulo', models.CharField(db_comment='TITULO DE LA TAREA')),
                ('descripcion', models.CharField(db_comment='DESCRIPCION DE LA TAREA')),
                ('comentario', models.CharField(blank=True, db_comment='COMENTARIO DE LA TAREA', null=True)),
                ('fecha_inicio_estimada', models.DateField(db_comment='FECHA ESTIMADA DE INICIO')),
                ('fecha_fin_estimada', models.DateField(db_comment='FECHA ESTIMADA DE FIN')),
                ('fecha_inicio_real', models.DateField(blank=True, db_comment='FECHA REAL DE INICIO', null=True)),
                ('fecha_fin_real', models.DateField(blank=True, db_comment='FECHA REAL DE FIN', null=True)),
                ('id_estado', models.ForeignKey(db_column='id_estado', db_comment='IDENTIFICADOR DE LA TAREA.', on_delete=django.db.models.deletion.CASCADE, to='app.estadotarea')),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', db_comment='IDENTIFICADOR DEL PROYECTO', on_delete=django.db.models.deletion.CASCADE, to='app.proyecto')),
            ],
            options={
                'db_table': 'tarea',
                'db_table_comment': 'TABLA DE LAS TAREAS RELACIONADAS A UN PROYECTO',
            },
        ),
    ]
